#!/bin/bash

# This script generates a human-readable system report with key OS, hardware, and network info.

# Get system hostname, current user, and date/time
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATETIME=$(date)

#This command loads OS name and version from system release file
source /etc/os-release
OS="$NAME $VERSION"

#This command get system uptime in a readable format 
UPTIME=$(uptime -p)

# This get CPU model name from hardware info
CPU=$(lshw -class processor 2>/dev/null | grep -m 1 'product:' | cut -d ':' -f2- | xargs)

# This command calculate installed RAM in GB by reading from /proc/meminfo and rounding
RAM=$(awk '/MemTotal/ {printf "%d GB", ($2 + 1048575) / 1024 / 1024}' /proc/meminfo)

# This command list all installed disks with make, model, and size
DISKS=$(lshw -class disk 2>/dev/null | awk -F: '/product:|size:/ {gsub(/^[ \t]+/, "", $2); printf "%s ", $2; if (NR % 2 == 0) print ""}')

# This get video card make and model from hardware info
VIDEO=$(lshw -class display 2>/dev/null | grep 'product:' | cut -d ':' -f2- | xargs)

# This identify network interface used for default route (main network connection)
DEFAULT_INTERFACE=$(ip route | awk '/default/ {print $5}' | head -n1)

# Get IP address for the interface connected to the default gateway
HOST_ADDRESS=$(ip -4 addr show "$DEFAULT_INTERFACE" | awk '/inet / {print $2}' | cut -d/ -f1)

# This get the IP address of the default gateway
GATEWAY_IP=$(ip route | awk '/default/ {print $3}' | head -n1)

# This command extract first DNS server IP from system resolver config
DNS_SERVER=$(grep "nameserver" /etc/resolv.conf | head -n1 | awk '{print $2}')

# List all currently logged-in users without duplicates 
LOGGED_USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd, -)

# This command get free space on local filesystems in /mountpoint size format
DISK_SPACE=$(df -h --output=target,avail,fstype | awk 'NR>1 && $3 ~ /ext4|xfs|btrfs/ {printf "%s %s, ", $1, $2}' | sed 's/, $//')

# Count all running processes
PROCESS_COUNT=$(ps ax | wc -l)

# Get system load averages for the past 1, 5, and 15 minutes
LOAD_AVERAGES=$(uptime | awk -F'load average:' '{ print $2 }' | xargs)

# Get list of ports currently being listened to (TCP/UDP)
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {split($5,a,":"); print a[length(a)]}' | sort -n | uniq | paste -sd, -)

# Check status of UFW (Uncomplicated Firewall)
UFW_STATUS=$(sudo ufw status | head -n1)

echo ""

cat <<EOF
System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $LOGGED_USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS
EOF

echo ""

